version: '3'
services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: woke_bot
      POSTGRES_DB: bot_repo 
    volumes:
      - bot-postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  bot:
    build:
      context: ./
      dockerfile: bot.Dockerfile
    depends_on:
      - db
    ports:
      - '3001:3001'
    environment:
      WAIT_HOSTS: db:5432
      POSTGRES_HOST: db,
      POSTGRES_PORT: 5432,

volumes:
  postgres_data:
