version: '3'
services:
  bot-db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: woke_bot
      POSTGRES_PASSWORD: woke_bot
      POSTGRES_DB: bot_db
    volumes:
      - bot-postgres_data:/var/lib/postgresql/data/
    ports:
      - '5433:5432'

  notifier:
    build:
      context: ./
      dockerfile: notifier.Dockerfile
    depends_on:
      - bot-db
    environment:
      WAIT_HOSTS: localhost:5432
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      NODE_ENV: 'development'
      PERSIST: 'true'
      DEBUG_RECOVERY: 'true'

  tipper:
    build:
      context: ./
      dockerfile: tipper.Dockerfile
    depends_on:
      - bot-db
    network_mode: host
    environment:
      WAIT_HOSTS: localhost:5432
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      NODE_ENV: 'development'
      PERSIST: 'true'
      DEBUG_RECOVERY: 'true'

volumes:
  bot-postgres_data:
