version: '3'
services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: woke_dapp 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  auth-server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    depends_on:
      - db
    ports:
      - '3001:3001'
      - '8443:8443'
    environment:
      WAIT_HOSTS: db:5432

volumes:
  postgres_data:
