version: '3'
services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: woke_dapp 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #ports:
      #- '5432:5432'
  auth-server:
    image: jvindustries/woke:server
    depends_on:
      - db
    ports:
      - '3001:3001'
      - '8443:8443'
    environment:
      NODE_ENV: production
      CONTEXT: production
      WOKE_ROLE: funder
      DEBUG: server*,actor*,sys_*
      ETH_ENV: production
      WAIT_HOSTS: db:5432

volumes:
  postgres_data:
