version: '3'
services:
  oracle-db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: woke_oracle
      POSTGRES_PWD: woke_oracle
      POSTGRES_DB: oracle_db
    volumes:
      - oracle_postgres_data:/var/lib/postgresql/data/
      #ports:
      #- '5433:5432'
  oracle:
    image: wokenetwork/woke:oracle
    depends_on:
      - oracle-db
    environment:
      PRINT_CONFIG: 'true'
      TWITTER_MENTIONS: 'false'
      EARLIEST_BLOCKNUMBER: 3197271
      NODE_ENV: 'staging'
      ETH_ENV: 'staging'
      TWITTER_ENV: 'staging'
      TWITTER_APP: 'staging-bot'
      WOKE_ROLE: 'oracle'
      NETWORK_LIST: 'goerli_infura,goerli_1'
      SUBSCRIPTION_WATCHDOG_INTERVAL: 300000
      VERBOSE: 'true'
      PERSIST: 'true'
      DEBUG_RECOVERY: 'true'
      POSTGRES_USER: woke_oracle
      POSTGRES_PWD: woke_oracle
      POSTGRES_DB: oracle_db
      POSTGRES_HOST: oracle-db
      POSTGRES_PORT: 5432
      WAIT_HOSTS: oracle-db:5432

volumes:
  oracle_postgres_data:
