version: '3'
services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: woke_dapp
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  server:
    network_mode: "host"
    build:
      context: ..
      dockerfile: ./docker/server.Dockerfile
    depends_on:
      - db
    ports:
      - '3001:3001'
      - '8443:8443'
    environment:
      PRINT_CONFIG: 'true'
      VERBOSE: 'true'
      PERSIST: 'false'
      PERSIST_ENV: 'development'
      TWITTER_ENV: 'dvelopment'
      DEBUG: '*,-sequelize:*,-express:router*,-*:info'
      # DEBUG: '*,-express:router*,-*:info'
      DEBUG_RECOVERY: 'true'
      WOKE_ROLE: funder
      NODE_ENV: development-docker
      ETH_ENV: development
      HOST_ENV: 'staging' # select staging ssl certs
      TWITTER_ENV: 'staging'
      TWITTER_APP: 'staging-bot'
      NETWORK_LIST: 'development'
      POSTGRES_HOST: 'localhost'
      # WAIT_HOSTS: db:5432

volumes:
  postgres_data:
