version: '3'
services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: woke_dapp 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  auth-server:
    network_mode: "host"
    build:
      context: ./
      dockerfile: server.Dockerfile
    depends_on:
      - db
    ports:
      - '3001:3001'
      - '8443:8443'
    environment:
      NODE_ENV: development-docker
      ETH_ENV: development
      DEBUG: server*,actor*
      CONTEXT: local
      POSTGRES_HOST: localhost
      WOKE_ROLE: funder
      WAIT_HOSTS: localhost:5432

volumes:
  postgres_data:
